DROP TABLE uiut_user_section_regions;
DROP TABLE uiut_regions;

SELECT * FROM all_tables
WHERE table_name LIKE 'UIUT%';

CREATE TABLE uiut_layouts (
    layout_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    layout_name VARCHAR2(255),
    CONSTRAINT uiut_layouts_uq 
        UNIQUE (layout_name)
);

CREATE TABLE uiut_regions (
    region_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    layout_id NUMBER NOT NULL,
    region_name VARCHAR2(512) NOT NULL,
    region_width_cols NUMBER NOT NULL,
    description VARCHAR2(4096),
    CONSTRAINT uiut_regions_region_width_cols_chk CHECK (region_width_cols BETWEEN 1 AND 12),
    CONSTRAINT uiut_regions_to_uiut_layouts_fk 
        FOREIGN KEY (layout_id)
        REFERENCES uiut_layouts (layout_id)
);

CREATE TABLE uiut_default_layout_regions (
    default_layout_region_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    region_id NUMBER NOT NULL,
    section_num NUMBER NOT NULL,
    region_order NUMBER NOT NULL,
    CONSTRAINT uiut_default_layout_regions_to_uiut_regions_fk 
        FOREIGN KEY (region_id)
        REFERENCES uiut_regions (region_id),
    CONSTRAINT uiut_default_layout_regions_uq UNIQUE (region_id)
);

CREATE TABLE uiut_user_section_regions (
    user_section_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_name VARCHAR2(255) NOT NULL,
    section_num NUMBER NOT NULL,
    region_order NUMBER NOT NULL,
    region_id NUMBER NOT NULL,
    CONSTRAINT uiut_user_section_regions_to_uiut_regions_fk
        FOREIGN KEY (region_id) 
        REFERENCES uiut_regions (region_id),
    CONSTRAINT uiut_user_section_regions_uq UNIQUE (user_name, region_id)
);
